export interface UpdateSizes {
  height?: number | null;
  weight?: number | null;
  sizeTopsAdmin?: number | null;
  sizeJacketAdmin?: number | null;
  sizeDropSizeAdmin?: number | null;
  shoulder?: number | null;
  shoulderJacket?: number | null;
  bust?: number | null;
  bustJacket?: number | null;
  lengthTop?: number | null;
  lengthTopJacket?: number | null;
  lengthArm?: number | null;
  lengthArmJacket?: number | null;
  waist?: number | null;
  hip?: number | null;
  roundLeg?: number | null;
  lengthLeg?: number | null;
  roundCalf?: number | null;
}
